### ISSUE TITLE
Download link invalid

### ISSUE THREAD

**Issue by jsunday** [bmullan/how-to_install_nuBuilder4#1]
Thank you for this tutorial.  I was able to follow it almost to the letter, but I was unable to locate and download the nubuilder file due to a bad link.  And I'm not sure of the correct link... but one time I was able to get it all running.  As I attempt it a second time I've failed.

Is it possible to change that line to the correct download link?  It is beyond my skills.

Again, thanks for the info already provide!

**Comment by bmullan** [comment]
I found this message on their Forum... apparently something is haywire on their website:

Re: User Guide for nuBuilder Forte

    kev1n wrote:
    Until the link works again, the User Guide can be downloaded from here:

    [nuBuilder User Guide](http://s000.tinyupload.com/index.php?fi ... 1203363142)
